# Generated by Django 3.0.6 on 2020-05-12 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DqDatafile',
            fields=[
                ('dq_datafile_id_pk', models.AutoField(primary_key=True, serialize=False)),
                ('data_file_name', models.CharField(blank=True, db_column='DATA_FILE_NAME', max_length=150, null=True)),
                ('data_file_type', models.CharField(blank=True, db_column='DATA_FILE_TYPE', max_length=50, null=True)),
                ('data_file_contact', models.CharField(blank=True, db_column='DATA_FILE_CONTACT', max_length=75, null=True)),
                ('contact_email', models.CharField(blank=True, db_column='CONTACT_EMAIL', max_length=150, null=True)),
                ('file_source', models.CharField(blank=True, db_column='FILE_SOURCE', max_length=50, null=True)),
                ('cadence', models.CharField(blank=True, db_column='CADENCE', max_length=50, null=True)),
                ('recurs_on_weekday', models.CharField(blank=True, db_column='RECURS_ON_WEEKDAY', max_length=50, null=True)),
                ('first_or_last', models.CharField(blank=True, db_column='FIRST_OR_LAST', max_length=10, null=True)),
                ('file_format', models.CharField(blank=True, db_column='FILE_FORMAT', max_length=50, null=True)),
                ('file_naming_convention', models.CharField(blank=True, db_column='FILE_NAMING_CONVENTION', max_length=200, null=True)),
                ('comments', models.TextField(blank=True, db_column='COMMENTS', null=True)),
                ('active_yn', models.CharField(blank=True, db_column='ACTIVE_YN', max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DqFeedNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dq_feed_id', models.IntegerField(db_column='DQ_FEED_ID')),
                ('source_datafile_name', models.CharField(blank=True, db_column='SOURCE_DATAFILE_NAME', max_length=150, null=True)),
                ('source_datafile_type', models.CharField(blank=True, db_column='SOURCE_DATAFILE_TYPE', max_length=25, null=True)),
                ('source_datafile_display', models.CharField(blank=True, db_column='SOURCE_DATAFILE_DISPLAY', max_length=150, null=True)),
                ('category', models.CharField(blank=True, db_column='CATEGORY', max_length=50, null=True)),
                ('received_date', models.DateTimeField(blank=True, db_column='RECEIVED_DATE', null=True)),
                ('total_rows_in_source_file', models.IntegerField(blank=True, db_column='TOTAL_ROWS_IN_SOURCE_FILE', null=True)),
                ('load_date', models.DateTimeField(blank=True, db_column='LOAD_DATE', null=True)),
                ('loaded_by', models.CharField(blank=True, db_column='LOADED_BY', max_length=50, null=True)),
                ('rows_loaded', models.IntegerField(blank=True, db_column='ROWS_LOADED', null=True)),
                ('rows_failed_to_load', models.IntegerField(blank=True, db_column='ROWS_FAILED_TO_LOAD', null=True)),
                ('create_dt', models.DateTimeField(blank=True, db_column='CREATE_DT', null=True)),
                ('update_dt', models.DateTimeField(blank=True, db_column='UPDATE_DT', null=True)),
                ('file_status', models.CharField(blank=True, db_column='FILE_STATUS', max_length=50, null=True)),
                ('number_of_files_loaded', models.IntegerField(blank=True, db_column='NUMBER_OF_FILES_LOADED', null=True)),
                ('expected_date', models.DateField(blank=True, db_column='EXPECTED_DATE', null=True)),
                ('dq_datafile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='calendarui.DqDatafile')),
            ],
        ),
    ]
