# Generated by Django 3.0.6 on 2020-05-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DqDatafile',
            fields=[
                ('dq_datafile_id', models.AutoField(db_column='DQ_DATAFILE_ID', primary_key=True, serialize=False)),
                ('data_file_name', models.CharField(blank=True, db_column='DATA_FILE_NAME', max_length=150, null=True)),
                ('data_file_type', models.CharField(blank=True, db_column='DATA_FILE_TYPE', max_length=50, null=True)),
                ('data_file_contact', models.CharField(blank=True, db_column='DATA_FILE_CONTACT', max_length=75, null=True)),
                ('contact_email', models.CharField(blank=True, db_column='CONTACT_EMAIL', max_length=150, null=True)),
                ('file_source', models.CharField(blank=True, db_column='FILE_SOURCE', max_length=50, null=True)),
                ('cadence', models.CharField(blank=True, db_column='CADENCE', max_length=50, null=True)),
                ('recurs_on_weekday', models.CharField(blank=True, db_column='RECURS_ON_WEEKDAY', max_length=50, null=True)),
                ('first_or_last', models.CharField(blank=True, db_column='FIRST_OR_LAST', max_length=10, null=True)),
                ('file_format', models.CharField(blank=True, db_column='FILE_FORMAT', max_length=50, null=True)),
                ('file_naming_convention', models.CharField(blank=True, db_column='FILE_NAMING_CONVENTION', max_length=200, null=True)),
                ('comments', models.TextField(blank=True, db_column='COMMENTS', null=True)),
                ('active_yn', models.CharField(blank=True, db_column='ACTIVE_YN', max_length=1, null=True)),
            ],
        ),
    ]
