# Generated by Django 3.0.6 on 2020-05-12 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarui', '0002_auto_20200512_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='dqdatafile',
            name='dq_feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calendarui.DqFeedNew'),
        ),
    ]
