# Generated by Django 3.0.6 on 2020-05-12 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarui', '0004_auto_20200512_1312'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DqFeed',
        ),
    ]
